In [15]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv('sample_data2.csv')

df.shape

In [17]:
df.shape

(9, 5)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Serial Number  9 non-null      int64
 1   Title          9 non-null      object
 2   Salary         8 non-null      float64
 3   Qualification  8 non-null      object
 4   Exp            9 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 492.0+ bytes

In [19]:
## to remove duplicates
df.duplicated().sum()

np.int64(1)

In [20]:
df[df.duplicated()]

   Serial Number      Title   Salary Qualification  Exp
5              4  Professor  25000.0     Bachelors    5

In [21]:
df.drop_duplicates(inplace = True,ignore_index = True)

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df

   Serial Number               Title   Salary Qualification  Exp
0              1   Software Engineer  20000.0     Bachelors    3
1              2      Data Scientist  23000.0       Masters    4
2              3     Project Manager  18000.0       Masters    2
3              4           Professor  25000.0     Bachelors    5
4              5  Database Architect  17000.0     Bachelors    1
5              7    Business Analyst  18000.0           NaN    5
6              8     UX/UI Developer     23.0     Bachelors    0
7              9     Devops Engineer      NaN       Masters    2

In [24]:
## handlings missing values
df.isnull().sum().sum()/df.size*100

np.float64(5.0)

In [11]:
df.dropna() ## to remove missing values

   Serial Number               Title   Salary Qualification  Exp
0              1   Software Engineer  20000.0     Bachelors    3
1              2      Data Scientist  23000.0       Masters    4
2              3     Project Manager  18000.0       Masters    2
3              4           Professor  25000.0     Bachelors    5
4              5  Database Architect  17000.0     Bachelors    1
6              8     UX/UI Developer     23.0     Bachelors    0

In [25]:
df.Salary.mean()

np.float64(17289.0)

In [26]:
df.Qualification.mode()

0    Bachelors
Name: Qualification, dtype: object

In [27]:
df.fillna({'Salary': df.Salary.mean(),'Qualification':df.Qualification.mode()[0]},inplace = True)

In [28]:
df.isnull().sum().sum()/df.size*100

np.float64(0.0)