In [1]:
import pandas as pd

In [3]:
## series
ser1 = pd.Series(data=[90,88,77,66,55,44],index=['ajay','sanjai','ramesh','suman','john','tom'])

In [4]:
ser1

ajay      90
sanjai    88
ramesh    77
suman     66
john      55
tom       44
dtype: int64

In [17]:
dict1= {'Name':['Ramesh','Sanjay','Ramya','Suman','John'],'Age':[22,25,30,28,32],

        'Gender':['Male','Male','Female','Female','Male'],

        'Location':['Bengaluru','Chennai','Pune','Bengaluru','Calcutta']}

In [18]:
df = pd.DataFrame(dict1,index = range(1,6))
df

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
5    John   32    Male   Calcutta

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 1 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      object
 1   Age       5 non-null      int64
 2   Gender    5 non-null      object
 3   Location  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [21]:
df.columns

Index(['Name', 'Age', 'Gender', 'Location'], dtype='object')

In [23]:
df.Gender

1      Male
2      Male
3    Female
4    Female
5      Male
Name: Gender, dtype: object

In [24]:
df

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
5    John   32    Male   Calcutta

In [26]:
df.Age.sort_values()

1    22
2    25
4    28
3    30
5    32
Name: Age, dtype: int64

In [27]:
df['Age'].sort_values()

1    22
2    25
4    28
3    30
5    32
Name: Age, dtype: int64

In [29]:
df.sort_values(by='Age')

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
4   Suman   28  Female  Bengaluru
3   Ramya   30  Female       Pune
5    John   32    Male   Calcutta

In [28]:
df.sort_values(by='Age',ascending=False)

     Name  Age  Gender   Location
5    John   32    Male   Calcutta
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
2  Sanjay   25    Male    Chennai
1  Ramesh   22    Male  Bengaluru

In [31]:
df.drop(columns = ['Gender'])

     Name  Age   Location
1  Ramesh   22  Bengaluru
2  Sanjay   25    Chennai
3   Ramya   30       Pune
4   Suman   28  Bengaluru
5    John   32   Calcutta

In [32]:
df

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
5    John   32    Male   Calcutta

In [ ]:
## if u want to delete a column permntely
df.drop(columns = ['Gender'],inplace = True)

In [40]:
df.rename(columns = {'Location':'place'})

     Name  Age  Gender      place
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
5    John   32    Male   Calcutta

In [39]:
df[(df.Gender == 'Male') & (df.Location == 'Chennai')]

     Name  Age Gender Location
2  Sanjay   25   Male  Chennai

In [41]:
df.Location.unique()

array(['Bengaluru', 'Chennai', 'Pune', 'Calcutta'], dtype=object)

In [47]:
df.Location.value_counts()

Location
Bengaluru    2
Chennai      1
Pune         1
Calcutta     1
Name: count, dtype: int64

In [50]:
df.Age.min()

22

In [51]:
df.Age.max()

32

In [52]:
df.Age.mean()

np.float64(27.4)

In [55]:
df.Age.median()

28.0

In [56]:
df.Age.mode()

0    22
1    25
2    28
3    30
4    32
Name: Age, dtype: int64

In [57]:
df.describe()

             Age
count   5.000000
mean   27.400000
std     3.974921
min    22.000000
25%    25.000000
50%    28.000000
75%    30.000000
max    32.000000

In [58]:
df.Name.describe()

count          5
unique         5
top       Ramesh
freq           1
Name: Name, dtype: object

In [59]:
df.describe(include = 'all')

          Name        Age Gender   Location
count        5   5.000000      5          5
unique       5        NaN      2          4
top     Ramesh        NaN   Male  Bengaluru
freq         1        NaN      3          2
mean       NaN  27.400000    NaN        NaN
std        NaN   3.974921    NaN        NaN
min        NaN  22.000000    NaN        NaN
25%        NaN  25.000000    NaN        NaN
50%        NaN  28.000000    NaN        NaN
75%        NaN  30.000000    NaN        NaN
max        NaN  32.000000    NaN        NaN

In [60]:
df.iloc[1]

Name         Sanjay
Age              25
Gender         Male
Location    Chennai
Name: 2, dtype: object

In [61]:
df.iloc[:3]

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune

In [63]:
df.iloc[[0,2,4],[0,2,3]]

     Name  Gender   Location
1  Ramesh    Male  Bengaluru
3   Ramya  Female       Pune
5    John    Male   Calcutta

In [64]:
## to find the column of a particular index
df.columns.get_loc('Gender')

2

In [65]:
df.loc[3]

Name         Ramya
Age             30
Gender      Female
Location      Pune
Name: 3, dtype: object

In [66]:
df.loc[1:4]

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru

In [70]:
df.loc[:,:'Gender']

     Name  Age  Gender
1  Ramesh   22    Male
2  Sanjay   25    Male
3   Ramya   30  Female
4   Suman   28  Female
5    John   32    Male

In [74]:
df.loc[[1,2,4],['Name','Gender','Location']]

     Name  Gender   Location
1  Ramesh    Male  Bengaluru
2  Sanjay    Male    Chennai
4   Suman  Female  Bengaluru

In [75]:
df = pd.read_csv('CARS_1.CSV')

In [77]:
df

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
0,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0,NaN
1,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0,NaN
2,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0,NaN
3,Acura,MDX,NaN,Asia,All,"$36,945",NaN,3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0,NaN
4,Acura,TL 4dr,NaN,Asia,Front,"$33,195",NaN,3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,NaN,group by,1) data will split,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,NaN,NaN,2) apply the function mean(mpg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,NaN,NaN,3) combine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
df = pd.read_csv('/Users/anu/Downloads/course/CARS_1.csv')
df

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
0,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0,NaN
1,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0,NaN
2,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0,NaN
3,Acura,MDX,NaN,Asia,All,"$36,945",NaN,3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0,NaN
4,Acura,TL 4dr,NaN,Asia,Front,"$33,195",NaN,3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,NaN,group by,1) data will split,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,NaN,NaN,2) apply the function mean(mpg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,NaN,NaN,3) combine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df.head()

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
0,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0,NaN
1,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0,NaN
2,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0,NaN
3,Acura,MDX,NaN,Asia,All,"$36,945",NaN,3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0,NaN
4,Acura,TL 4dr,NaN,Asia,Front,"$33,195",NaN,3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0,NaN

In [85]:
df.tail()

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,NaN,group by,1) data will split,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,NaN,NaN,2) apply the function mean(mpg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,NaN,NaN,3) combine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
df.shape

(443, 16)

In [87]:
df.size

7088

In [88]:
len(df)

443

In [90]:
df.columns

Index(['name_of_car', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP',
       'Invoice', 'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City',
       'MPG_Highway', 'Weight', 'Wheelbase', 'Length', 'Unnamed: 15'],
      dtype='object')

In [89]:
len(df.columns)

16

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name_of_car  428 non-null    object
 1   Model        429 non-null    object
 2   Type         409 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    object
 6   Invoice      406 non-null    object
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   343 non-null    float64
 10  MPG_City     428 non-null    float64
 11  MPG_Highway  428 non-null    float64
 12  Weight       428 non-null    float64
 13  Wheelbase    428 non-null    float64
 14  Length       428 non-null    float64
 15  Unnamed: 15  2 non-null      float64
dtypes: float64(9), object(7)
memory usage: 55.5+ KB

In [94]:
df.isnull().sum()

name_of_car     15
Model           14
Type            34
Origin          15
DriveTrain      15
MSRP            15
Invoice         37
EngineSize      15
Cylinders       17
Horsepower     100
MPG_City        15
MPG_Highway     15
Weight          15
Wheelbase       15
Length          15
Unnamed: 15    441
dtype: int64

In [95]:
df.isnull()

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True
4,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
439,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
440,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
441,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True
442,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True