In [2]:
import pandas as pd

In [3]:
## series
ser1 = pd.Series(data=[90,88,77,66,55,44],index=['ajay','sanjai','ramesh','suman','john','tom'])

In [4]:
ser1

ajay      90
sanjai    88
ramesh    77
suman     66
john      55
tom       44
dtype: int64

In [17]:
dict1= {'Name':['Ramesh','Sanjay','Ramya','Suman','John'],'Age':[22,25,30,28,32],

        'Gender':['Male','Male','Female','Female','Male'],

        'Location':['Bengaluru','Chennai','Pune','Bengaluru','Calcutta']}

In [18]:
df = pd.DataFrame(dict1,index = range(1,6))
df

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
5    John   32    Male   Calcutta

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 1 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      5 non-null      object
 1   Age       5 non-null      int64
 2   Gender    5 non-null      object
 3   Location  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [21]:
df.columns

Index(['Name', 'Age', 'Gender', 'Location'], dtype='object')

In [23]:
df.Gender

1      Male
2      Male
3    Female
4    Female
5      Male
Name: Gender, dtype: object

In [24]:
df

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
5    John   32    Male   Calcutta

In [26]:
df.Age.sort_values()

1    22
2    25
4    28
3    30
5    32
Name: Age, dtype: int64

In [27]:
df['Age'].sort_values()

1    22
2    25
4    28
3    30
5    32
Name: Age, dtype: int64

In [29]:
df.sort_values(by='Age')

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
4   Suman   28  Female  Bengaluru
3   Ramya   30  Female       Pune
5    John   32    Male   Calcutta

In [28]:
df.sort_values(by='Age',ascending=False)

     Name  Age  Gender   Location
5    John   32    Male   Calcutta
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
2  Sanjay   25    Male    Chennai
1  Ramesh   22    Male  Bengaluru

In [31]:
df.drop(columns = ['Gender'])

     Name  Age   Location
1  Ramesh   22  Bengaluru
2  Sanjay   25    Chennai
3   Ramya   30       Pune
4   Suman   28  Bengaluru
5    John   32   Calcutta

In [32]:
df

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
5    John   32    Male   Calcutta

In [ ]:
## if u want to delete a column permntely
df.drop(columns = ['Gender'],inplace = True)

In [40]:
df.rename(columns = {'Location':'place'})

     Name  Age  Gender      place
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru
5    John   32    Male   Calcutta

In [39]:
df[(df.Gender == 'Male') & (df.Location == 'Chennai')]

     Name  Age Gender Location
2  Sanjay   25   Male  Chennai

In [41]:
df.Location.unique()

array(['Bengaluru', 'Chennai', 'Pune', 'Calcutta'], dtype=object)

In [47]:
df.Location.value_counts()

Location
Bengaluru    2
Chennai      1
Pune         1
Calcutta     1
Name: count, dtype: int64

In [50]:
df.Age.min()

22

In [51]:
df.Age.max()

32

In [52]:
df.Age.mean()

np.float64(27.4)

In [55]:
df.Age.median()

28.0

In [56]:
df.Age.mode()

0    22
1    25
2    28
3    30
4    32
Name: Age, dtype: int64

In [57]:
df.describe()

             Age
count   5.000000
mean   27.400000
std     3.974921
min    22.000000
25%    25.000000
50%    28.000000
75%    30.000000
max    32.000000

In [58]:
df.Name.describe()

count          5
unique         5
top       Ramesh
freq           1
Name: Name, dtype: object

In [59]:
df.describe(include = 'all')

          Name        Age Gender   Location
count        5   5.000000      5          5
unique       5        NaN      2          4
top     Ramesh        NaN   Male  Bengaluru
freq         1        NaN      3          2
mean       NaN  27.400000    NaN        NaN
std        NaN   3.974921    NaN        NaN
min        NaN  22.000000    NaN        NaN
25%        NaN  25.000000    NaN        NaN
50%        NaN  28.000000    NaN        NaN
75%        NaN  30.000000    NaN        NaN
max        NaN  32.000000    NaN        NaN

In [60]:
df.iloc[1]

Name         Sanjay
Age              25
Gender         Male
Location    Chennai
Name: 2, dtype: object

In [61]:
df.iloc[:3]

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune

In [63]:
df.iloc[[0,2,4],[0,2,3]]

     Name  Gender   Location
1  Ramesh    Male  Bengaluru
3   Ramya  Female       Pune
5    John    Male   Calcutta

In [64]:
## to find the column of a particular index
df.columns.get_loc('Gender')

2

In [65]:
df.loc[3]

Name         Ramya
Age             30
Gender      Female
Location      Pune
Name: 3, dtype: object

In [66]:
df.loc[1:4]

     Name  Age  Gender   Location
1  Ramesh   22    Male  Bengaluru
2  Sanjay   25    Male    Chennai
3   Ramya   30  Female       Pune
4   Suman   28  Female  Bengaluru

In [70]:
df.loc[:,:'Gender']

     Name  Age  Gender
1  Ramesh   22    Male
2  Sanjay   25    Male
3   Ramya   30  Female
4   Suman   28  Female
5    John   32    Male

In [74]:
df.loc[[1,2,4],['Name','Gender','Location']]

     Name  Gender   Location
1  Ramesh    Male  Bengaluru
2  Sanjay    Male    Chennai
4   Suman  Female  Bengaluru

In [75]:
df = pd.read_csv('CARS_1.CSV')

In [77]:
df

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
0,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0,NaN
1,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0,NaN
2,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0,NaN
3,Acura,MDX,NaN,Asia,All,"$36,945",NaN,3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0,NaN
4,Acura,TL 4dr,NaN,Asia,Front,"$33,195",NaN,3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,NaN,group by,1) data will split,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,NaN,NaN,2) apply the function mean(mpg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,NaN,NaN,3) combine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df = pd.read_csv('/Users/anu/Downloads/course/CARS_1.csv')
df

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
0,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0,NaN
1,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0,NaN
2,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0,NaN
3,Acura,MDX,NaN,Asia,All,"$36,945",NaN,3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0,NaN
4,Acura,TL 4dr,NaN,Asia,Front,"$33,195",NaN,3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,NaN,group by,1) data will split,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,NaN,NaN,2) apply the function mean(mpg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,NaN,NaN,3) combine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head()

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
0,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0,NaN
1,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0,NaN
2,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0,NaN
3,Acura,MDX,NaN,Asia,All,"$36,945",NaN,3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0,NaN
4,Acura,TL 4dr,NaN,Asia,Front,"$33,195",NaN,3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0,NaN

In [5]:
df.tail()

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,NaN,group by,1) data will split,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,NaN,NaN,2) apply the function mean(mpg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,NaN,NaN,3) combine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(443, 16)

In [7]:
df.size

7088

In [8]:
len(df)

443

In [9]:
df.columns

Index(['name_of_car', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP',
       'Invoice', 'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City',
       'MPG_Highway', 'Weight', 'Wheelbase', 'Length', 'Unnamed: 15'],
      dtype='object')

In [10]:
len(df.columns)

16

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name_of_car  428 non-null    object
 1   Model        429 non-null    object
 2   Type         409 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    object
 6   Invoice      406 non-null    object
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   343 non-null    float64
 10  MPG_City     428 non-null    float64
 11  MPG_Highway  428 non-null    float64
 12  Weight       428 non-null    float64
 13  Wheelbase    428 non-null    float64
 14  Length       428 non-null    float64
 15  Unnamed: 15  2 non-null      float64
dtypes: float64(9), object(7)
memory usage: 55.5+ KB

In [12]:
df.isnull().sum()

name_of_car     15
Model           14
Type            34
Origin          15
DriveTrain      15
MSRP            15
Invoice         37
EngineSize      15
Cylinders       17
Horsepower     100
MPG_City        15
MPG_Highway     15
Weight          15
Wheelbase       15
Length          15
Unnamed: 15    441
dtype: int64

In [95]:
df.isnull()

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True
4,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
439,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
440,True,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
441,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True
442,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True

In [96]:
git add .

SyntaxError: invalid syntax (3827820173.py, line 1)

In [97]:
!git add .

In [98]:
!git commit -m 'pandas added'

[main 5278f32] pandas added
 5 files changed, 4122 insertions(+), 1 deletion(-)
 create mode 100644 .DS_Store
 create mode 100644 CARS_1.csv
 create mode 100644 numpy.ipynb
 create mode 100644 pandas.ipynb

In [99]:
!git push

Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 20.88 KiB | 6.96 MiB/s, done.
Total 7 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/sanjai570/data-science.git
   21ee256..5278f32  main -> main

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name_of_car  428 non-null    object
 1   Model        429 non-null    object
 2   Type         409 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    object
 6   Invoice      406 non-null    object
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   343 non-null    float64
 10  MPG_City     428 non-null    float64
 11  MPG_Highway  428 non-null    float64
 12  Weight       428 non-null    float64
 13  Wheelbase    428 non-null    float64
 14  Length       428 non-null    float64
 15  Unnamed: 15  2 non-null      float64
dtypes: float64(9), object(7)
memory usage: 55.5+ KB

In [14]:
df.isnull().sum()

name_of_car     15
Model           14
Type            34
Origin          15
DriveTrain      15
MSRP            15
Invoice         37
EngineSize      15
Cylinders       17
Horsepower     100
MPG_City        15
MPG_Highway     15
Weight          15
Wheelbase       15
Length          15
Unnamed: 15    441
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(11)

In [17]:
df[df.duplicated()]

,name_of_car,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Unnamed: 15
429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.columns

Index(['name_of_car', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP',
       'Invoice', 'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City',
       'MPG_Highway', 'Weight', 'Wheelbase', 'Length', 'Unnamed: 15'],
      dtype='object')

In [22]:
df.EngineSize.kurt()

np.float64(0.5419435377632986)

In [23]:
df.EngineSize.skew()

np.float64(0.7081519824692281)

In [26]:
## crosstab

df.name_of_car.unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'GMC', 'Honda', 'Hummer', 'Hyundai',
       'Infiniti', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
       'Lexus', 'Lincoln', 'Mazda', 'Mercedes-Benz', 'Mercury', 'MINI',
       'Mitsubishi', 'Nissan', 'Oldsmobile', 'Pontiac', 'Porsche', 'Saab',
       'Saturn', 'Scion', 'Subaru', 'Suzuki', 'Toyota', 'Volkswagen',
       'Volvo', nan], dtype=object)

In [28]:
df.Origin.unique()

array(['Asia', 'Europe', 'USA', nan], dtype=object)

In [29]:
pd.crosstab(index = df.name_of_car,columns = df.Origin)

Origin         Asia  Europe  USA
name_of_car
Acura             7       0    0
Audi              0      19    0
BMW               0      20    0
Buick             0       0    9
Cadillac          0       0    8
Chevrolet         0       0   27
Chrysler          0       0   15
Dodge             0       0   13
Ford              0       0   23
GMC               0       0    8
Honda            17       0    0
Hummer            0       0    1
Hyundai          12       0    0
Infiniti          8       0    0
Isuzu             2       0    0
Jaguar            0      12    0
Jeep              0       0    3
Kia              11       0    0
Land Rover        0       3    0
Lexus            11       0    0
Lincoln           0       0    9
MINI              0       2    0
Mazda            11       0    0
Mercedes-Benz     0      26    0
Mercury           0       0    9
Mitsubishi       13       0    0
Nissan           17       0    0
Oldsmobile        0       0    3
Pontiac           0       0   11
Porsche           0       7    0
Saab              0       7    0
Saturn            0       0    8
Scion             2       0    0
Subaru           11       0    0
Suzuki            8       0    0
Toyota           28       0    0
Volkswagen        0      15    0
Volvo             0      12    0

In [30]:
pd.crosstab(index = [df.name_of_car,df.Model],columns = df.Origin)

Origin                               Asia  Europe  USA
name_of_car Model
Acura       3.5 RL 4dr                  1       0    0
            3.5 RL w/Navigation 4dr     1       0    0
            MDX                         1       0    0
            NSX coupe 2dr manual S      1       0    0
            RSX Type S 2dr              1       0    0
...                                   ...     ...  ...
Volvo       S80 2.9 4dr                 0       1    0
            S80 T6 4dr                  0       1    0
            V40                         0       1    0
            XC70                        0       1    0
            XC90 T6                     0       1    0

[425 rows x 3 columns]

In [31]:
df.groupby('Origin')['EngineSize'].agg(['mean','max','min','count','sum','median'])

            mean  max  min  count    sum  median
Origin
Asia    2.774051  5.6  1.3    158  438.3     2.6
Europe  3.206504  6.0  1.6    123  394.4     3.0
USA     3.642857  8.3  1.6    147  535.5     3.6

In [32]:
df.groupby('Origin')[['EngineSize','Cylinders','Horsepower']].max()

        EngineSize  Cylinders  Horsepower
Origin
Asia           5.6        8.0       340.0
Europe         6.0       12.0       493.0
USA            8.3       10.0       500.0

In [33]:
## pivot table

In [34]:
df.pivot_table(index = 'name_of_car',columns = 'Origin',values = 'EngineSize',aggfunc = ['median','mean','max','min','sum'])

              median                   mean                      max         \
Origin          Asia Europe   USA      Asia    Europe       USA Asia Europe
name_of_car
Acura           3.20    NaN   NaN  3.042857       NaN       NaN  3.5    NaN
Audi             NaN    3.0   NaN       NaN  3.057895       NaN  NaN    4.2
BMW              NaN    3.0   NaN       NaN  3.125000       NaN  NaN    4.4
Buick            NaN    NaN  3.80       NaN       NaN  3.722222  NaN    NaN
Cadillac         NaN    NaN  4.60       NaN       NaN  4.737500  NaN    NaN
Chevrolet        NaN    NaN  3.50       NaN       NaN  3.733333  NaN    NaN
Chrysler         NaN    NaN  2.70       NaN       NaN  2.960000  NaN    NaN
Dodge            NaN    NaN  3.50       NaN       NaN  3.484615  NaN    NaN
Ford             NaN    NaN  3.80       NaN       NaN  3.552174  NaN    NaN
GMC              NaN    NaN  4.55       NaN       NaN  4.650000  NaN    NaN
Honda           2.40    NaN   NaN  2.382353       NaN       NaN  3.5    NaN
Hummer           NaN    NaN  6.00       NaN       NaN  6.000000  NaN    NaN
Hyundai         2.35    NaN   NaN  2.383333       NaN       NaN  3.5    NaN
Infiniti        3.50    NaN   NaN  3.875000       NaN       NaN  4.5    NaN
Isuzu           3.70    NaN   NaN  3.700000       NaN       NaN  4.2    NaN
Jaguar           NaN    4.2   NaN       NaN  3.858333       NaN  NaN    4.2
Jeep             NaN    NaN  4.00       NaN       NaN  3.466667  NaN    NaN
Kia             1.80    NaN   NaN  2.345455       NaN       NaN  3.5    NaN
Land Rover       NaN    4.4   NaN       NaN  3.833333       NaN  NaN    4.6
Lexus           3.30    NaN   NaN  3.718182       NaN       NaN  4.7    NaN
Lincoln          NaN    NaN  4.60       NaN       NaN  4.177778  NaN    NaN
MINI             NaN    1.6   NaN       NaN  1.600000       NaN  NaN    1.6
Mazda           2.00    NaN   NaN  2.190909       NaN       NaN  4.0    NaN
Mercedes-Benz    NaN    3.2   NaN       NaN  3.903846       NaN  NaN    5.5
Mercury          NaN    NaN  4.20       NaN       NaN  3.955556  NaN    NaN
Mitsubishi      2.40    NaN   NaN  2.776923       NaN       NaN  3.8    NaN
Nissan          3.50    NaN   NaN  3.405882       NaN       NaN  5.6    NaN
Oldsmobile       NaN    NaN  3.40       NaN       NaN  3.000000  NaN    NaN
Pontiac          NaN    NaN  3.40       NaN       NaN  3.427273  NaN    NaN
Porsche          NaN    3.6   NaN       NaN  3.542857       NaN  NaN    4.5
Saab             NaN    2.0   NaN       NaN  2.128571       NaN  NaN    2.3
Saturn           NaN    NaN  2.20       NaN       NaN  2.300000  NaN    NaN
Scion           1.50    NaN   NaN  1.500000       NaN       NaN  1.5    NaN
Subaru          2.50    NaN   NaN  2.545455       NaN       NaN  3.0    NaN
Suzuki          2.30    NaN   NaN  2.325000       NaN       NaN  2.7    NaN
Toyota          2.70    NaN   NaN  2.682143       NaN       NaN  4.7    NaN
Volkswagen       NaN    2.0   NaN       NaN  2.806667       NaN  NaN    6.0
Volvo            NaN    2.5   NaN       NaN  2.458333       NaN  NaN    2.9

                    min               sum
Origin         USA Asia Europe  USA  Asia Europe    USA
name_of_car
Acura          NaN  2.0    NaN  NaN  21.3    NaN    NaN
Audi           NaN  NaN    1.8  NaN   NaN   58.1    NaN
BMW            NaN  NaN    2.5  NaN   NaN   62.5    NaN
Buick          4.2  NaN    NaN  3.1   NaN    NaN   33.5
Cadillac       6.0  NaN    NaN  3.6   NaN    NaN   37.9
Chevrolet      6.0  NaN    NaN  1.6   NaN    NaN  100.8
Chrysler       3.8  NaN    NaN  2.4   NaN    NaN   44.4
Dodge          8.3  NaN    NaN  2.0   NaN    NaN   45.3
Ford           6.8  NaN    NaN  2.0   NaN    NaN   81.7
GMC            6.0  NaN    NaN  2.8   NaN    NaN   37.2
Honda          NaN  1.4    NaN  NaN  40.5    NaN    NaN
Hummer         6.0  NaN    NaN  6.0   NaN    NaN    6.0
Hyundai        NaN  1.6    NaN  NaN  28.6    NaN    NaN
Infiniti       NaN  3.5    NaN  NaN  31.0    NaN    NaN
Isuzu          NaN  3.2    NaN  NaN   7.4    NaN    NaN
Jaguar         NaN  NaN    2.5  NaN   NaN   46.3    NaN
Jeep           4.0  NaN    NaN  2.4   NaN    NaN   10.4
Kia            NaN  1.6    NaN  NaN  25.8    NaN    NaN
Land Rover     NaN  NaN    2.5  NaN   NaN   11.5    NaN
Lexus          NaN  3.0    NaN  NaN  40.9    NaN    NaN
Lincoln        5.4  NaN    NaN  3.0   NaN    NaN   37.6
MINI           NaN  NaN    1.6  NaN   NaN    3.2    NaN
Mazda          NaN  1.3    NaN  NaN  24.1    NaN    NaN
Mercedes-Benz  NaN  NaN    1.8  NaN   NaN  101.5    NaN
Mercury        4.6  NaN    NaN  3.0   NaN    NaN   35.6
Mitsubishi     NaN  2.0    NaN  NaN  36.1    NaN    NaN
Nissan         NaN  1.8    NaN  NaN  57.9    NaN    NaN
Oldsmobile     3.4  NaN    NaN  2.2   NaN    NaN    9.0
Pontiac        5.7  NaN    NaN  1.8   NaN    NaN   37.7
Porsche        NaN  NaN    2.7  NaN   NaN   24.8    NaN
Saab           NaN  NaN    2.0  NaN   NaN   14.9    NaN
Saturn         3.0  NaN    NaN  2.2   NaN    NaN   18.4
Scion          NaN  1.5    NaN  NaN   3.0    NaN    NaN
Subaru         NaN  2.0    NaN  NaN  28.0    NaN    NaN
Suzuki         NaN  2.0    NaN  NaN  18.6    NaN    NaN
Toyota         NaN  1.5    NaN  NaN  75.1    NaN    NaN
Volkswagen     NaN  NaN    1.8  NaN   NaN   42.1    NaN
Volvo          NaN  NaN    1.9  NaN   NaN   29.5    NaN

In [35]:
df.pivot_table(index = ['name_of_car','Model'],columns = 'Origin',values = 'EngineSize',aggfunc = ['median','mean','max','min','sum'])

                                    median            mean             max  \
Origin                                Asia Europe USA Asia Europe USA Asia
name_of_car Model
Acura       3.5 RL 4dr                 3.5    NaN NaN  3.5    NaN NaN  3.5
            3.5 RL w/Navigation 4dr    3.5    NaN NaN  3.5    NaN NaN  3.5
            MDX                        3.5    NaN NaN  3.5    NaN NaN  3.5
            NSX coupe 2dr manual S     3.2    NaN NaN  3.2    NaN NaN  3.2
            RSX Type S 2dr             2.0    NaN NaN  2.0    NaN NaN  2.0
...                                    ...    ...  ..  ...    ...  ..  ...
Volvo       S80 2.9 4dr                NaN    2.9 NaN  NaN    2.9 NaN  NaN
            S80 T6 4dr                 NaN    2.9 NaN  NaN    2.9 NaN  NaN
            V40                        NaN    1.9 NaN  NaN    1.9 NaN  NaN
            XC70                       NaN    2.5 NaN  NaN    2.5 NaN  NaN
            XC90 T6                    NaN    2.9 NaN  NaN    2.9 NaN  NaN

                                                min             sum
Origin                              Europe USA Asia Europe USA Asia Europe USA
name_of_car Model
Acura       3.5 RL 4dr                 NaN NaN  3.5    NaN NaN  3.5    NaN NaN
            3.5 RL w/Navigation 4dr    NaN NaN  3.5    NaN NaN  3.5    NaN NaN
            MDX                        NaN NaN  3.5    NaN NaN  3.5    NaN NaN
            NSX coupe 2dr manual S     NaN NaN  3.2    NaN NaN  3.2    NaN NaN
            RSX Type S 2dr             NaN NaN  2.0    NaN NaN  2.0    NaN NaN
...                                    ...  ..  ...    ...  ..  ...    ...  ..
Volvo       S80 2.9 4dr                2.9 NaN  NaN    2.9 NaN  NaN    2.9 NaN
            S80 T6 4dr                 2.9 NaN  NaN    2.9 NaN  NaN    2.9 NaN
            V40                        1.9 NaN  NaN    1.9 NaN  NaN    1.9 NaN
            XC70                       2.5 NaN  NaN    2.5 NaN  NaN    2.5 NaN
            XC90 T6                    2.9 NaN  NaN    2.9 NaN  NaN    2.9 NaN

[425 rows x 15 columns]

In [36]:
dict1={'names':['ajay','sanjay','raheem','sudha','loha'],'course':['python','python','java','R','R'],'marks':[7,8,2,1,5]}

dict2={'names':['basha','sam','suji'],'course':['java','DA','AI'],'marks':[4,7,8],'location':['mumbai','calcutta','orissa']}

 

dict3= {'names':['sanjay','raheem','sudha','raja'],'groups':[1,2,3,4]}

In [37]:
df1= pd.DataFrame(dict1)

df2= pd.DataFrame(dict2)

df3= pd.DataFrame(dict3)

In [38]:
pd.concat([df1,df2])

    names  course  marks  location
0    ajay  python      7       NaN
1  sanjay  python      8       NaN
2  raheem    java      2       NaN
3   sudha       R      1       NaN
4    loha       R      5       NaN
0   basha    java      4    mumbai
1     sam      DA      7  calcutta
2    suji      AI      8    orissa

In [39]:
pd.concat([df1,df2],ignore_index = True)

    names  course  marks  location
0    ajay  python      7       NaN
1  sanjay  python      8       NaN
2  raheem    java      2       NaN
3   sudha       R      1       NaN
4    loha       R      5       NaN
5   basha    java      4    mumbai
6     sam      DA      7  calcutta
7    suji      AI      8    orissa

In [42]:
pd.concat([df1,df2],axis = 1)

    names  course  marks  names course  marks  location
0    ajay  python      7  basha   java    4.0    mumbai
1  sanjay  python      8    sam     DA    7.0  calcutta
2  raheem    java      2   suji     AI    8.0    orissa
3   sudha       R      1    NaN    NaN    NaN       NaN
4    loha       R      5    NaN    NaN    NaN       NaN

In [45]:
!git add .

In [46]:
!git commit -m 'pandas added'

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

In [47]:
!git push

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 68.46 KiB | 13.69 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/sanjai570/data-science.git
   5278f32..7dedfa3  main -> main